[package]
name = "mxpir"
version = "0.1.0"
authors = ["Sebastian Angel <sebs@cs.utexas.edu>"]

[dependencies]
xpir = { path = "../xpir-rust/" }
rust-crypto = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
num = "*"
rand = "*"
criterion = "*"
